name: _body_only
timestamp: 1486509906
version: 7
preset:
  image: 'gantry-admin://images/layouts/body-only.png'
  name: _body_only
  timestamp: 1472071076
positions: {  }
sections:
  main: Main
particles:
  messages:
    system-messages-3574: 'System Messages'
  content:
    system-content-3895: 'Page Content'
inherit: {  }
