ordering:
  home: ''
  tour: ''
  about: ''
  hiring: ''
  blog: ''
  features:
    -
      layout-manager: ''
      menu-editor: ''
      particles: ''
      typography: ''
      uikit-framework: ''
      documentation: ''
    -
      module-variations: ''
      scrollreveal-js: ''
      contacts: ''
      pricing: ''
      gallery: ''
      faq: ''
    -
      our-team: ''
      downloads: ''
      video-showcase: ''
      app-merchandise: ''
      app-reviews: ''
      call-to-actions: ''
    -
      single-article: ''
      category-blog: ''
      search-results: ''
      member-login: ''
      joomla-registration: ''
      404-error-page: ''
  presets:
    preset1: ''
    preset2: ''
    preset3: ''
    preset4: ''
    preset5: ''
    preset6: ''
items:
  features:
    id: 109
    columns:
      - 25
      - 25
      - 25
      - 25
  presets:
    id: 108
    hash: ''
    dropdown_dir: right
    dropdown_hide: ''
    width: auto
    class: presets-demo
  presets/preset1:
    id: 138
    hash: ''
    dropdown_dir: right
    dropdown_hide: ''
    width: auto
    class: preset1
  presets/preset2:
    id: 139
    hash: ''
    dropdown_dir: right
    dropdown_hide: ''
    width: auto
    class: preset2
  presets/preset3:
    id: 140
    hash: ''
    dropdown_dir: right
    dropdown_hide: ''
    width: auto
    class: preset3
  presets/preset4:
    id: 141
    hash: ''
    dropdown_dir: right
    dropdown_hide: ''
    width: auto
    class: preset4
  presets/preset5:
    id: 142
    hash: ''
    dropdown_dir: right
    dropdown_hide: ''
    width: auto
    class: preset5
  presets/preset6:
    id: 143
    hash: ''
    dropdown_dir: right
    dropdown_hide: ''
    width: auto
    class: preset6
